#!/usr/bin/env python

import sys, os
import getopt

# Local imports
from defs import *
from PageRange import *

if __name__ == "__main__":
    # Configuration
    config = {
        'overlap': 5, # mm
        'page_size': (210, 297), # A4
        'page_border': 10, # mm
        'map_file': "foo.mapnik",
        'output': "map.pdf",
        'ranges': [{
            'id': 'main',
            'bounds': (13.8528, 48.6887, 13.898, 48.713),
            'scale': 20000
        },
#        {
#            'include_page_bounds': [ 'main' ],
#            'bounds': (13.785, 48.764, 14.064, 48.545),
#            'scale': 140000
#        }
        ]
    }

    # Load Page Ranges
    page_ranges = []
    sum_pages = 0
    for range in config['ranges']:
        for k, v in config.iteritems():
            if not k in range:
                range[k] = v;

        range['page_number_offset'] = sum_pages

        current = PageRange(range)
        page_ranges.append(current)

        sum_pages += current.count_pages()
        print sum_pages

    # Produce final PDF
    final_pdf = PDF.PdfFileWriter()
    for range in page_ranges:
        range.render(final_pdf)

    final_pdf.write(file(config['output'], 'wb'))
