#!/usr/bin/env python

import sys, os
import getopt

# Local imports
from defs import *
from PageRange import *

if __name__ == "__main__":
    # Configuration
    config = {
        'overlap': 5, # mm
        'page_size': (210, 297), # A4
        'page_border': 5, # mm
        'map_file': "foo.mapnik",
        'output': "map.pdf",
        'ranges': [{
            'bounds': (15.4410,47.072,15.4451,47.0664),
            'scale': 2000
        }]
    }

    # Load Page Ranges
    page_ranges = []
    for range in config['ranges']:
        for k, v in config.iteritems():
            if not k in range:
                range[k] = v;

        page_ranges.append(PageRange(range))
